
dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
description: "A new Flutter application."
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.7.0 <3.0.0"
flutter:
  assets:
    - images/diamond.png
  uses-material-design: true
name: i_am_rich
publish_to: ~
version: 1.0.0+1
